source 'https://rubygems.org'

gem 'telegram-bot-ruby'
gem 'rest_client'
gem 'gruff'
gem 'activerecord', '~>4.0.0'
gem 'activesupport', '~>4.0.0'
gem 'pry'
gem 'rake'
gem 'sqlite3'
gem 'nokogiri'
gem 'rufus-scheduler'